apiVersion: apps/v1
kind: Deployment
metadata:
    name: activity-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            component: web
    template:
        metadata:
            labels:
                component: web
        spec:
            containers:
                 - image: docker.io/caddy
                   name: client
                   ports:
                      - containerPort: 80